### ISSUE TITLE
Мысли для SMACSS-квеста

### ISSUE THREAD

**Issue by juwain** [tsergeytovarov/ac-first-quest#1]
### Базовая стилизация

Методология допускает применение базовых стилей по тегу для задания общих значений по всему сайту. Не рекомендуется использовать important или жёсткий reset всех отступов. Пример:

```
body, form {
  margin: 0;
  padding: 0; 
}
```

Вариант задания: базовые стили для общих элементов.
Правильно: по тегу, по классу.
Неправильно: по какому-нибудь вычурному чрезмерно длинному или непонятному классу.
### Лейаут

SMACSS допускает использование id для стилизации крупных блоков типа общей шапки или подвала сайта. Но лучше эту тему не поднимать.

Для разметочных классов можно ставить префикс `.l-` или `.layout-`. Допускается привязываться к структуре сетки, если она в теории не меняется.

```
.l-grid {
  margin: 0;
  padding: 0;
  list-style-type: none;
}
.l-grid > li {
  display: inline-block;
  margin: 0 0 10px 10px;
}
```

Вариант задания: назвать класс для разметочных блоков.
Правильный вариант: с префиксом `.l-`.
Неправильный вариант: излишне специфичный селектор или наоборот стилизация блока разметки по тегу.
### Модули

Классы модулей не прификсуются.
Не приветствуется привязка к структуре блока. Можно включать название блока в классы элементов. Плохо — `.block > span`, `#sidebar div h3`, хорошо – `.block, .block-field, .block-title`.

Допускается задавать уточняющие подклассы модулям. Например:

```
<div class="block block-short">
  <h1 class="block-title"></h1>
</div>

.block {}

.block-title {}

.block-shirt {}

.block-shirt .block-title {}
```

Вариант задания: дать класс модулю или элементу модуля.
Правильный вариант: неспецифичный селектор по классу (`.block-shirt`), класс с названием модуля (`.block-title`).
Неправильный вариант: специфичный селектор с каскадом (`#sidebar .block input[type=text]`).
### Состояние

Префиксуется `.is-`.

Описывает состояние модуля или лейаута.
Вариант задания: Состояния модулей типа `is-collapsed`, `is-active`.
Правильный вариант: когда описывается состояние модуля, которое может измениться (`class="block is-hidden"`).
Неправильный вариант: когда путаются состояние и модификатор (`class="button is-big-button"`)
### Темы

В наших макетах не затрагивается.

**Comment by tsergeytovarov** [comment]
Смотри первый квест

Первый блок
header - неверно, так как на семантические элементы мы без класса не вешаем стили
.l-header - лучший вариант с использованием .l-
.main-header - допустимый вариант

Второй блок
.logo - лучший вариант просто по классу. 
img - в данном случае недопустимо, так как картинок много может быть
.container .logo - неверно так как специфично

Третий блок
А вот тут ты мне ответь что правильно, а что нет))

Четвертый блок
.features-item - лучший вариант
article - нет так как семантический элемент
.features .feature - нет так как специфично

Пятый блок
.features-item > h1 - не очень так как специфично и не факт что h1 не изменится 
h1 - точно нет, так как уже использовано выше
.feature-title - лучший вариант

Шестой блок
.feature-text - лучший вариант
.features-item > p - допустимо так как внутри будет параграф
p - тоже допустимо?? или все таки тут нестандартное оформление и он не подходит

Седьмой блок
.section-title - допустимо
h2 - лучше всего 
section .title - слтшком специфично

Восьмой блок
div - конечно нет
.main-footer .social-block - можно но специфично
footer > .social-block - слишком специфично так что нет
.social-block - лучший вариант

**Comment by juwain** [comment]
В общем, Смакс в целом рекомендательная штука. Так что говорить, что решение прям неверно, не всегда правильно.

> Первый блок
> header - неверно, так как на семантические элементы мы без класса не вешаем стили
> .l-header - лучший вариант с использованием .l-
> .main-header - допустимый вариант

Согласен со всем, кроме `.l-header`. С префиксом `.l-` идут общие блоки исключительно для раскладки. Типа нашего любимого `center-wrapper` или всяких `side-col`,`main-col` ) `.l-header` в данном случае — слишком частное название. С `.l-` уместнее будет дать название для общего контейнера `.l-container`, например.

> .container .logo - неверно так как специфично

Какбе да, тут нежелательный каскад, от которого можно избавиться. Так делать нежелательно.

> Третий блок
> А вот тут ты мне ответь что правильно, а что нет))

`.statistic .title` — нежелательный каскад, от которого можно избавиться.
`.statistic h1` — тут такой момент, что заголовок `h1` по-любому один на странице и не возникнет случайного переопределения, так что вариант менее желательный из-за каскада, но допустимый.
`.statistic-title` — правильно.
`h1` – неправильно, слишком общий селектор.

> Пятый блок
> .features-item > h1 - не очень так как специфично и не факт что h1 не изменится 
> h1 - точно нет, так как уже использовано выше
> .feature-title - лучший вариант

`.features-item > h1` этот вариант не допустим в принципе, т.к. предполагает, что на странице будет больше одно заголовка `h1`, что неверно. Если бы был заголовок `h2`, то уже бы можно было зачесть в целом.

> Шестой блок
> .feature-text - лучший вариант
> .features-item > p - допустимо так как внутри будет параграф
> p - тоже допустимо?? или все таки тут нестандартное оформление и он не подходит

`p` будет иметь по-любому какие базовые стили, но в контексте этого модуля последний вариант не подходит.
